### ISSUE TITLE
Delivery address output

### ISSUE THREAD

**Issue by ChinJunAn** [AY2223S2-CS2103-F11-2/tp#144]
Is this intentional?
![image](https://user-images.githubusercontent.com/30628325/228126076-562e9f56-537b-4234-bdaf-247a72f3cd41.png)

**Comment by dohaduong** [comment]
Yep i think it's gonna be re-defined later, @c0j0s can you help confirm?

**Comment by c0j0s** [comment]
it should display something if the job is valid with a sender and a recipient. i guess we need to enforce it somewhere.
