### ISSUE TITLE
Edit job function cannot submit edit if recipient field is empty

### ISSUE THREAD

**Issue by ChinJunAn** [AY2223S2-CS2103-F11-2/tp#145]
Im not sure if this is a bug, but some of the test jobs added had their recipient field empty at the start. Should we allow edit job function to edit other fields (earnings, date, etc), but still leave the recipient field empty?

This is not app breaking bug fyi

**Comment by c0j0s** [comment]
There is a mandatory validation for recipient field, so normal creation shld be no issue.
Is it possible to post you job data file here? I'll try to replicate the issue from my side.

**Comment by ChinJunAn** [comment]
I dunno how upload file, but these are the corresponding json data

{
    "jobId" : "IRRO6A2F3C",
    "earning" : "4.0",
    "isDelivered" : false,
    "description" : "",
    "recipient" : null,
    "sender" : "ROY926",
    "deliveryDate" : "2023-03-02",
    "deliverySlot" : "5"
  }, {
    "jobId" : "ROALF63585",
    "earning" : "5.0",
    "isDelivered" : false,
    "description" : "",
    "recipient" : null,
    "sender" : "ALE874",
    "deliveryDate" : "0000-00-00",
    "deliverySlot" : "-1"
  }
