### ISSUE TITLE
[Notification] NullPointerException at checkNextSchedule during launch?

### ISSUE THREAD

**Issue by c0j0s** [AY2223S2-CS2103-F11-2/tp#157]
![image](https://user-images.githubusercontent.com/7760148/228299829-3661b6a5-5972-46aa-a42c-060b3e82e5ef.png)

```java
        if (hour < 10) {
            jobList = deliveryList.get(0);
        }
```

**Comment by ChinJunAn** [comment]
Could you try again with the current master? I cannot reproduce the bug
